;;; agents-turn-diff-test.el --- Turn diff regression checks -*- lexical-binding: t; -*-
(require 'ert)
(require 'agents)

(ert-deftest agents-turn-diff-uses-captured-patch ()
  (let ((agent (generate-new-buffer " *turn-diff-test*"))
        (patch "--- a/code.el\n+++ b/code.el\n@@ -1 +1 @@\n-old\n+new\n"))
    (unwind-protect
        (cl-letf (((symbol-function 'agents--diff-insert)
                   (lambda (_) (insert "unrelated old working-tree change")))
                  ((symbol-function 'display-buffer) (lambda (&rest _) nil)))
          (agents--diff-show agent `((file . "/tmp/code.el") (diff . ,patch)))
          (with-current-buffer (agents--diff-buffer-name agent)
            (should (equal (buffer-string) patch))))
      (when-let* ((diff (get-buffer (agents--diff-buffer-name agent)))) (kill-buffer diff))
      (kill-buffer agent))))

(require 'jgy-agent-diff)

(defun jgy-agent-diff-test--git (dir &rest args)
  (apply #'jgy-agent-diff--git dir "-c" "user.name=Test" "-c"
         "user.email=test@example.invalid" "-c" "commit.gpgsign=false" args))

(defun jgy-agent-diff-test--write (dir name text)
  (with-temp-file (expand-file-name name dir) (insert text)))

(defmacro jgy-agent-diff-test--repo (&rest body)
  (declare (indent 0))
  `(let ((dir (make-temp-file "turn-repo-" t)))
     (unwind-protect
         (with-temp-buffer
           (jgy-agent-diff-test--git dir "init" "-q")
           ,@body)
       (delete-directory dir t))))

(ert-deftest jgy-agent-diff-dirty-baseline-survives-commit ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-test--write dir "project.md" "base\n")
    (jgy-agent-diff-test--write dir "clean.el" "old\n")
    (jgy-agent-diff-test--git dir "add" ".")
    (jgy-agent-diff-test--git dir "commit" "-qm" "initial")
    (jgy-agent-diff-test--write dir "project.md" "base\nuser todo\n")
    ;; Staged dirt is part of the starting working-tree content too.
    (jgy-agent-diff-test--git dir "add" "project.md")
    (jgy-agent-diff-begin dir)
    (should (= 1 (hash-table-count (plist-get (car jgy-agent-diff--repos) :base))))
    (should-not (jgy-agent-diff-scan))
    (jgy-agent-diff-test--write dir "project.md" "base\nuser todo\nagent log\n")
    (jgy-agent-diff-test--write dir "clean.el" "new\n")
    ;; One shell invocation can write AND commit before the next scan.
    (jgy-agent-diff-test--git dir "add" ".")
    (jgy-agent-diff-test--git dir "commit" "-qm" "changes")
    (should (jgy-agent-diff-scan))
    (let* ((entry (cl-find (expand-file-name "project.md" dir) jgy-agent-diff--files
                           :key (lambda (row) (alist-get 'file row)) :test #'equal))
           (patch (alist-get 'diff entry))
           (files (copy-tree jgy-agent-diff--files)))
      (should (string-match-p "\n[+]agent log" patch))
      (should (string-match-p "\n user todo" patch))
      (should-not (string-match-p "\n[+]user todo" patch))
      (should (= 1 (alist-get 'added entry)))
      (should (numberp (alist-get 'line entry)))
      (should-not (jgy-agent-diff-scan))
      (should (equal files jgy-agent-diff--files))
      (jgy-agent-diff-test--git dir "commit" "--allow-empty" "-qm" "no content change")
      (should-not (jgy-agent-diff-scan))
      (should (equal files jgy-agent-diff--files)))
    (jgy-agent-diff-begin dir)
    (should-not jgy-agent-diff--files)
    (should (= 0 (hash-table-count (plist-get (car jgy-agent-diff--repos) :base))))
    (should-not (jgy-agent-diff-scan))))

(ert-deftest jgy-agent-diff-new-deleted-restored-and-untracked ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-test--write dir "old.txt" "old\n")
    (jgy-agent-diff-test--git dir "add" ".")
    (jgy-agent-diff-test--git dir "commit" "-qm" "initial")
    (jgy-agent-diff-test--write dir "draft.txt" "existing draft\n")
    (jgy-agent-diff-begin dir)
    (delete-file (expand-file-name "old.txt" dir))
    (jgy-agent-diff-test--write dir "draft.txt" "existing draft\nnew line\n")
    (jgy-agent-diff-test--write dir "new name.txt" "brand new\n")
    (should (jgy-agent-diff-scan))
    (should (= 3 (length jgy-agent-diff--files)))
    (let ((patches (mapconcat (lambda (row) (alist-get 'diff row)) jgy-agent-diff--files "")))
      (should (string-match-p "+++ /dev/null" patches))
      (should (string-match-p "--- /dev/null" patches))
      (should (string-match-p "\n[+]brand new" patches))
      (should (string-match-p "\n existing draft" patches)))
    (jgy-agent-diff-test--write dir "old.txt" "old\n")
    (should (jgy-agent-diff-scan))
    (should (equal "" (alist-get 'diff (car (last jgy-agent-diff--files)))))
    (should-not (jgy-agent-diff-scan))))

(ert-deftest jgy-agent-diff-nested-repos-and-subdirectory ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-test--write dir ".gitignore" "project/code/\n")
    (make-directory (expand-file-name "project/code" dir) t)
    (let ((root (expand-file-name "project" dir))
          (code (expand-file-name "project/code" dir)))
      (jgy-agent-diff-test--write root "project.md" "before\n")
      (jgy-agent-diff-test--git dir "add" ".")
      (jgy-agent-diff-test--git dir "commit" "-qm" "workspace")
      (jgy-agent-diff-test--git code "init" "-q")
      (jgy-agent-diff-test--write code "code.el" "before\n")
      (jgy-agent-diff-test--git code "add" ".")
      (jgy-agent-diff-test--git code "commit" "-qm" "code")
      (jgy-agent-diff-begin root)
      (should (= 2 (length jgy-agent-diff--repos)))
      (jgy-agent-diff-test--write root "project.md" "after\n")
      (jgy-agent-diff-test--write code "code.el" "after\n")
      (should (jgy-agent-diff-scan))
      (should (= 2 (length jgy-agent-diff--files)))
      (dolist (entry jgy-agent-diff--files)
        (should (string-match-p "\n-before\n[+]after" (alist-get 'diff entry)))))))

(ert-deftest jgy-agent-diff-unborn-repo-and-skip-binary ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-test--write dir "draft" "before\n")
    (jgy-agent-diff-test--write dir "binary" "a\0b")
    (jgy-agent-diff-begin dir)
    (jgy-agent-diff-test--write dir "draft" "after\n")
    (jgy-agent-diff-test--write dir "binary" "c\0d")
    (jgy-agent-diff-test--git dir "add" ".")
    (jgy-agent-diff-test--git dir "commit" "-qm" "first")
    (should (jgy-agent-diff-scan))
    (should (= 1 (length jgy-agent-diff--files)))
    (should (string-match-p "\n-before\n[+]after" (alist-get 'diff (car jgy-agent-diff--files))))))

(ert-deftest agents-turn-diff-keeps-current-on-ambiguous-batch ()
  (let* ((a '((file . "a") (diff . "old")))
         (b '((file . "b") (diff . "new")))
         (c '((file . "c") (diff . "new"))))
    (should-not (agents--diff-latest (list a) (list a b c) "a"))
    (should (equal b (agents--diff-latest (list a) (list a b) "a")))
    (should (equal b (agents--diff-latest nil (list b c) "b")))))

(require 'jgy-agent-shell)
(ert-deftest jgy-agent-diff-event-lifecycle ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-test--write dir "file.txt" "before\n")
    (jgy-agent-diff-test--git dir "add" ".")
    (jgy-agent-diff-test--git dir "commit" "-qm" "initial")
    (setq agents-identity `((root . ,dir))
          agents--diff-follow '(:files nil :file nil))
    (cl-letf (((symbol-function 'agents-report) #'ignore)
              ((symbol-function 'agents-dashboard-refresh) #'ignore)
              ((symbol-function 'display-buffer) (lambda (&rest _) nil)))
      (unwind-protect
          (progn
            (jgy/agent-shell--on-event '((:event . input-submitted)))
            (jgy-agent-diff-test--write dir "file.txt" "after\n")
            (jgy-agent-diff-test--git dir "add" ".")
            (jgy-agent-diff-test--git dir "commit" "-qm" "change")
            (jgy/agent-shell--on-event
             '((:event . tool-call-update) (:data (:tool-call (:kind . "execute") (:status . "completed")))))
            (should (= 1 (length (jgy/agent-shell--files))))
            (agents--diff-show (current-buffer) (car (jgy/agent-shell--files)))
            (let ((patch (alist-get 'diff (car (jgy/agent-shell--files)))))
              (jgy/agent-shell--on-event '((:event . turn-complete)))
              (should (equal patch (alist-get 'diff (car (jgy/agent-shell--files)))))
              (jgy/agent-shell--on-event '((:event . input-submitted)))
              (should-not (jgy/agent-shell--files))
              (with-current-buffer (agents--diff-buffer-name (current-buffer))
                (should (equal patch (buffer-string)))
                (should (string-prefix-p "Previous turn" header-line-format)))))
        (when-let* ((diff (get-buffer (agents--diff-buffer-name (current-buffer)))))
          (kill-buffer diff))))))

(ert-deftest jgy-agent-diff-empty-file-and-relative-path ()
  (jgy-agent-diff-test--repo
    (make-directory (expand-file-name "sub" dir))
    (jgy-agent-diff-begin dir)
    (jgy-agent-diff-test--write dir "sub/empty" "")
    (should (jgy-agent-diff-scan))
    (let ((entry (car jgy-agent-diff--files)))
      (should (equal (alist-get 'directory entry) (file-name-as-directory dir)))
      (should (equal (alist-get 'diff entry) "--- /dev/null\n+++ b/sub/empty\n"))
      (should (= 0 (alist-get 'added entry))))))
