;;; jgy-agents-turn-diff-test.el --- Turn diff regression checks -*- lexical-binding: t; -*-
(require 'ert)
(require 'jgy-agents-follow)

(ert-deftest jgy-agents-turn-diff-uses-captured-patch ()
  (let ((agent (generate-new-buffer " *turn-diff-test*"))
        (patch "--- a/code.el\n+++ b/code.el\n@@ -1 +1 @@\n-old\n+new\n"))
    (unwind-protect
        (cl-letf (((symbol-function 'jgy-agents-follow--insert)
                   (lambda (_) (insert "unrelated old working-tree change")))
                  ((symbol-function 'display-buffer) (lambda (&rest _) nil)))
          (jgy-agents-follow--show agent `((file . "/tmp/code.el") (diff . ,patch)))
          (with-current-buffer (jgy-agents-follow--buffer-name agent)
            (should (equal (buffer-string) patch))))
      (when-let* ((diff (get-buffer (jgy-agents-follow--buffer-name agent)))) (kill-buffer diff))
      (kill-buffer agent))))

(require 'jgy-agent-diff)

(defun jgy-agent-diff-test--git (dir &rest args)
  (apply #'jgy-agent-diff--git dir "-c" "user.name=Test" "-c"
         "user.email=test@example.invalid" "-c" "commit.gpgsign=false" args))

(defun jgy-agent-diff-test--write (dir name text)
  (with-temp-file (expand-file-name name dir) (insert text)))

(defmacro jgy-agent-diff-test--repo (&rest body)
  (declare (indent 0))
  `(let ((dir (make-temp-file "turn-repo-" t)))
     (unwind-protect
         (with-temp-buffer
           (jgy-agent-diff-test--git dir "init" "-q")
           ,@body)
       (delete-directory dir t))))

(defun jgy-agent-diff-test--drain ()
  "Wait for real subprocesses and timers, with a bounded deadline."
  (let ((deadline (+ (float-time) 10)))
    (while (and (< (float-time) deadline)
                (or jgy-agent-diff--timer jgy-agent-diff--iterator jgy-agent-diff--pending))
      (accept-process-output nil 0.01))
    (should-not jgy-agent-diff--iterator)
    (should-not jgy-agent-diff--pending)
    (should-not jgy-agent-diff--timer)))

(defun jgy-agent-diff-test--scan ()
  (let ((before (copy-tree jgy-agent-diff--files)))
    (jgy-agent-diff-request)
    (jgy-agent-diff-test--drain)
    (not (equal before jgy-agent-diff--files))))

(ert-deftest jgy-agent-diff-dirty-baseline-survives-commit ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-test--write dir "project.md" "base\n")
    (jgy-agent-diff-test--write dir "clean.el" "old\n")
    (jgy-agent-diff-test--git dir "add" ".")
    (jgy-agent-diff-test--git dir "commit" "-qm" "initial")
    (jgy-agent-diff-test--write dir "project.md" "base\nuser todo\n")
    ;; Staged dirt is part of the starting working-tree content too.
    (jgy-agent-diff-test--git dir "add" "project.md")
    (jgy-agent-diff-begin dir)
    (should (= 1 (hash-table-count (plist-get (car jgy-agent-diff--repos) :base))))
    (should-not (jgy-agent-diff-test--scan))
    (jgy-agent-diff-test--write dir "project.md" "base\nuser todo\nagent log\n")
    (jgy-agent-diff-test--write dir "clean.el" "new\n")
    ;; One shell invocation can write AND commit before the next scan.
    (jgy-agent-diff-test--git dir "add" ".")
    (jgy-agent-diff-test--git dir "commit" "-qm" "changes")
    (should (jgy-agent-diff-test--scan))
    (let* ((entry (cl-find (expand-file-name "project.md" dir) jgy-agent-diff--files
                           :key (lambda (row) (alist-get 'file row)) :test #'equal))
           (patch (alist-get 'diff entry))
           (files (copy-tree jgy-agent-diff--files)))
      (should (string-match-p "\n[+]agent log" patch))
      (should (string-match-p "\n user todo" patch))
      (should-not (string-match-p "\n[+]user todo" patch))
      (should (= 1 (alist-get 'added entry)))
      (should (numberp (alist-get 'line entry)))
      (should-not (jgy-agent-diff-test--scan))
      (should (equal files jgy-agent-diff--files))
      (jgy-agent-diff-test--git dir "commit" "--allow-empty" "-qm" "no content change")
      (should-not (jgy-agent-diff-test--scan))
      (should (equal files jgy-agent-diff--files)))
    (jgy-agent-diff-begin dir)
    (should-not jgy-agent-diff--files)
    (should (= 0 (hash-table-count (plist-get (car jgy-agent-diff--repos) :base))))
    (should-not (jgy-agent-diff-test--scan))))

(ert-deftest jgy-agent-diff-new-deleted-restored-and-untracked ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-test--write dir "old.txt" "old\n")
    (jgy-agent-diff-test--git dir "add" ".")
    (jgy-agent-diff-test--git dir "commit" "-qm" "initial")
    (jgy-agent-diff-test--write dir "draft.txt" "existing draft\n")
    (jgy-agent-diff-begin dir)
    (delete-file (expand-file-name "old.txt" dir))
    (jgy-agent-diff-test--write dir "draft.txt" "existing draft\nnew line\n")
    (jgy-agent-diff-test--write dir "new name.txt" "brand new\n")
    (should (jgy-agent-diff-test--scan))
    (should (= 3 (length jgy-agent-diff--files)))
    (let ((patches (mapconcat (lambda (row) (alist-get 'diff row)) jgy-agent-diff--files "")))
      (should (string-match-p "+++ /dev/null" patches))
      (should (string-match-p "--- /dev/null" patches))
      (should (string-match-p "\n[+]brand new" patches))
      (should (string-match-p "\n existing draft" patches)))
    (jgy-agent-diff-test--write dir "old.txt" "old\n")
    (should (jgy-agent-diff-test--scan))
    (should (equal "" (alist-get 'diff (car (last jgy-agent-diff--files)))))
    (should-not (jgy-agent-diff-test--scan))))

(ert-deftest jgy-agent-diff-nested-repos-and-subdirectory ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-test--write dir ".gitignore" "project/code/\n")
    (make-directory (expand-file-name "project/code" dir) t)
    (let ((root (expand-file-name "project" dir))
          (code (expand-file-name "project/code" dir)))
      (jgy-agent-diff-test--write root "project.md" "before\n")
      (jgy-agent-diff-test--git dir "add" ".")
      (jgy-agent-diff-test--git dir "commit" "-qm" "workspace")
      (jgy-agent-diff-test--git code "init" "-q")
      (jgy-agent-diff-test--write code "code.el" "before\n")
      (jgy-agent-diff-test--git code "add" ".")
      (jgy-agent-diff-test--git code "commit" "-qm" "code")
      (jgy-agent-diff-begin root)
      (should (= 2 (length jgy-agent-diff--repos)))
      (jgy-agent-diff-test--write root "project.md" "after\n")
      (jgy-agent-diff-test--write code "code.el" "after\n")
      (should (jgy-agent-diff-test--scan))
      (should (= 2 (length jgy-agent-diff--files)))
      (dolist (entry jgy-agent-diff--files)
        (should (string-match-p "\n-before\n[+]after" (alist-get 'diff entry)))))))

(ert-deftest jgy-agent-diff-unborn-repo-and-skip-binary ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-test--write dir "draft" "before\n")
    (jgy-agent-diff-test--write dir "binary" "a\0b")
    (jgy-agent-diff-begin dir)
    (jgy-agent-diff-test--write dir "draft" "after\n")
    (jgy-agent-diff-test--write dir "binary" "c\0d")
    (jgy-agent-diff-test--git dir "add" ".")
    (jgy-agent-diff-test--git dir "commit" "-qm" "first")
    (should (jgy-agent-diff-test--scan))
    (should (= 1 (length jgy-agent-diff--files)))
    (should (string-match-p "\n-before\n[+]after" (alist-get 'diff (car jgy-agent-diff--files))))))

(ert-deftest jgy-agents-turn-diff-keeps-current-on-ambiguous-batch ()
  (let* ((a '((file . "a") (diff . "old")))
         (b '((file . "b") (diff . "new")))
         (c '((file . "c") (diff . "new"))))
    (should-not (jgy-agents-follow--latest (list a) (list a b c) "a"))
    (should (equal b (jgy-agents-follow--latest (list a) (list a b) "a")))
    (should (equal b (jgy-agents-follow--latest nil (list b c) "b")))))

(require 'jgy-agent-shell)
(ert-deftest jgy-agent-diff-event-lifecycle ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-test--write dir "file.txt" "before\n")
    (jgy-agent-diff-test--git dir "add" ".")
    (jgy-agent-diff-test--git dir "commit" "-qm" "initial")
    (setq jgy-agents-identity `((root . ,dir))
          jgy-agents-follow--state '(:files nil :file nil))
    (cl-letf (((symbol-function 'jgy-agents-refresh) #'ignore)
              ((symbol-function 'display-buffer) (lambda (&rest _) nil)))
      (unwind-protect
          (progn
            (jgy-agent-shell--on-event '((:event . input-submitted)))
            (jgy-agent-diff-test--write dir "file.txt" "after\n")
            (jgy-agent-diff-test--git dir "add" ".")
            (jgy-agent-diff-test--git dir "commit" "-qm" "change")
            (jgy-agent-shell--on-event
             '((:event . tool-call-update) (:data (:tool-call (:kind . "execute") (:status . "completed")))))
            (jgy-agent-diff-test--drain)
            (should (= 1 (length (jgy-agent-shell--files))))
            (jgy-agents-follow--show (current-buffer) (car (jgy-agent-shell--files)))
            (let ((patch (alist-get 'diff (car (jgy-agent-shell--files)))))
              (jgy-agent-shell--on-event '((:event . turn-complete)))
              (jgy-agent-diff-test--drain)
              (should (equal patch (alist-get 'diff (car (jgy-agent-shell--files)))))
              (jgy-agent-shell--on-event '((:event . input-submitted)))
              (should-not (jgy-agent-shell--files))
              (with-current-buffer (jgy-agents-follow--buffer-name (current-buffer))
                (should (equal patch (buffer-string)))
                (should (string-prefix-p "Previous turn" header-line-format)))))
        (when-let* ((diff (get-buffer (jgy-agents-follow--buffer-name (current-buffer)))))
          (kill-buffer diff))))))

(ert-deftest jgy-agent-diff-empty-file-and-relative-path ()
  (jgy-agent-diff-test--repo
    (make-directory (expand-file-name "sub" dir))
    (jgy-agent-diff-begin dir)
    (jgy-agent-diff-test--write dir "sub/empty" "")
    (should (jgy-agent-diff-test--scan))
    (let ((entry (car jgy-agent-diff--files)))
      (should (equal (alist-get 'directory entry) (file-name-as-directory dir)))
      (should (equal (alist-get 'diff entry) "--- /dev/null\n+++ b/sub/empty\n"))
      (should (= 0 (alist-get 'added entry))))))

(ert-deftest jgy-agent-diff-readonly-dedupe-and-coalesce ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-begin dir)
    (dotimes (i 20)
      (jgy-agent-diff-tool i '((:kind . "read") (:status . "completed"))))
    (should-not jgy-agent-diff--pending)
    (should-not jgy-agent-diff--timer)
    (jgy-agent-diff-tool "shell" '((:kind . "execute") (:status . "failed")))
    (let ((timer jgy-agent-diff--timer))
      (dotimes (_ 20)
        (jgy-agent-diff-tool "shell" '((:kind . "execute") (:status . "failed"))))
      (should (eq timer jgy-agent-diff--timer)))
    (jgy-agent-diff-test--drain)
    (jgy-agent-diff-tool "shell" '((:kind . "execute") (:status . "failed")))
    (should-not jgy-agent-diff--pending)))

(ert-deftest jgy-agent-diff-targeted-edit-and-new-line ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-test--write dir "code" "old\n")
    (jgy-agent-diff-test--write dir "unrelated" "user draft\n")
    (jgy-agent-diff-begin dir)
    (let* ((path (expand-file-name "code" dir))
           (reads nil) (reader (symbol-function 'jgy-agent-diff--read)))
      (cl-letf (((symbol-function 'jgy-agent-diff--read)
                 (lambda (file) (push file reads) (funcall reader file))))
        (jgy-agent-diff-test--write dir "code" "first\n")
        (jgy-agent-diff-tool "edit1"
                            `((:kind . "edit") (:status . "completed")
                              (:locations . [((path . ,path) (line . 12))])))
        (jgy-agent-diff-test--drain)
        (should (equal reads (list path)))
        (should (= 12 (alist-get 'line (car jgy-agent-diff--files))))
        (jgy-agent-diff-test--write dir "code" "second\n")
        (jgy-agent-diff-tool "edit2"
                            `((:kind . "edit") (:status . "completed")
                              (:diffs . (((:file . ,path) (:line . 90))))))
        (jgy-agent-diff-test--drain)
        (should (= 90 (alist-get 'line (car jgy-agent-diff--files))))
        (should (alist-get 'active (car jgy-agent-diff--files)))))))

(ert-deftest jgy-agent-diff-final-finds-missing-event-and-freezes ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-begin dir)
    (jgy-agent-diff-test--write dir "missed" "change\n")
    (jgy-agent-diff-request nil nil t)
    (jgy-agent-diff-test--drain)
    (should (= 1 (length jgy-agent-diff--files)))
    (let ((files (copy-tree jgy-agent-diff--files)))
      (jgy-agent-diff-test--write dir "missed" "later\n")
      (jgy-agent-diff-tool "late" '((:kind . "execute") (:status . "completed")))
      (should-not jgy-agent-diff--pending)
      (should (equal files jgy-agent-diff--files)))))

(ert-deftest jgy-agent-diff-cancel-running-worker-on-new-turn ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-begin dir)
    (jgy-agent-diff-test--write dir "old-turn" "change\n")
    (setq jgy-agent-diff--pending t)
    (jgy-agent-diff--start)
    (should (processp jgy-agent-diff--process))
    (let ((process jgy-agent-diff--process)
          (generation jgy-agent-diff--generation))
      (jgy-agent-diff-begin dir)
      (should (> jgy-agent-diff--generation generation))
      (should-not (process-live-p process))
      (accept-process-output nil 0.05)
      (should-not jgy-agent-diff--files)
      (should-not jgy-agent-diff--iterator)
      (should-not (jgy-agent-diff-test--scan)))))

(ert-deftest jgy-agent-diff-final-queues-behind-running-worker ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-begin dir)
    (setq jgy-agent-diff--pending t)
    (jgy-agent-diff--start)
    (let ((process jgy-agent-diff--process))
      (jgy-agent-diff-test--write dir "last" "late change\n")
      (jgy-agent-diff-request nil nil t)
      (should (eq process jgy-agent-diff--process))
      (should (eq t jgy-agent-diff--pending)))
    (jgy-agent-diff-test--drain)
    (should (= 1 (length jgy-agent-diff--files)))))

(ert-deftest jgy-agent-diff-coalesced-edits-follow-last-explicit-target ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-begin dir)
    (dolist (name '("z-first" "a-last"))
      (jgy-agent-diff-test--write dir name "new\n")
      (let ((path (expand-file-name name dir)))
        (jgy-agent-diff-tool name
                            `((:kind . "edit") (:status . "completed")
                              (:diffs . (((:file . ,path) (:line . 1))))))))
    (jgy-agent-diff-test--drain)
    (let ((latest (jgy-agents-follow--latest nil jgy-agent-diff--files)))
      (should (equal (alist-get 'file latest) (expand-file-name "a-last" dir))))
    (let ((before (copy-tree jgy-agent-diff--files)))
      (jgy-agent-diff-request nil nil t)
      (jgy-agent-diff-test--drain)
      (should (equal before jgy-agent-diff--files)))))

(ert-deftest jgy-agents-turn-diff-cleared-focus-does-not-masquerade-as-edit ()
  (let ((old '(((file . "a") (diff . "old") (active . t))))
        (new '(((file . "a") (diff . "old") (active . nil))
               ((file . "b") (diff . "new") (active . nil)))))
    (should (equal "b" (alist-get 'file (jgy-agents-follow--latest old new "a"))))))

(ert-deftest jgy-agent-diff-final-verifies-content-despite-identical-stamp ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-test--write dir "file" "before\n")
    (cl-letf (((symbol-function 'jgy-agent-diff--stamp) (lambda (_) 'same)))
      (jgy-agent-diff-begin dir)
      (jgy-agent-diff-test--write dir "file" "after!\n")
      (should-not (jgy-agent-diff-test--scan))
      (jgy-agent-diff-request nil nil t)
      (jgy-agent-diff-test--drain)
      (should (string-match-p "[+]after!" (alist-get 'diff (car jgy-agent-diff--files)))))))

(ert-deftest jgy-agent-diff-targeted-ignore-and-outside-boundary ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-test--write dir ".gitignore" "ignored\n")
    (jgy-agent-diff-begin dir)
    (jgy-agent-diff-test--write dir "ignored" "private\n")
    (let ((path (expand-file-name "ignored" dir)))
      (jgy-agent-diff-request (list path "/outside/not-in-project") (list (cons path 1))))
    (jgy-agent-diff-test--drain)
    (should-not jgy-agent-diff--files)))

(ert-deftest jgy-agent-diff-second-hunk-navigation ()
  (jgy-agent-diff-test--repo
    (let* ((path (expand-file-name "code" dir))
           (lines (cl-loop for i from 1 to 100 collect (format "line %d\n" i))))
      (jgy-agent-diff-test--write dir "code" (apply #'concat lines))
      (jgy-agent-diff-begin dir)
      (setf (nth 11 lines) "first edit\n")
      (jgy-agent-diff-test--write dir "code" (apply #'concat lines))
      (jgy-agent-diff-request (list path) (list (cons path 12)))
      (jgy-agent-diff-test--drain)
      (setf (nth 89 lines) "second edit\n")
      (jgy-agent-diff-test--write dir "code" (apply #'concat lines))
      (jgy-agent-diff-request (list path) (list (cons path 90)))
      (jgy-agent-diff-test--drain)
      (let ((entry (car jgy-agent-diff--files)))
        (with-temp-buffer
          (insert (alist-get 'diff entry))
          (goto-char (jgy-agents-follow--hunk (alist-get 'line entry)))
          (should (looking-at "@@ -87,7 [+]87,7 @@")))))))

(ert-deftest jgy-agent-diff-cancel-cleans-pending-patch-files ()
  (jgy-agent-diff-test--repo
    (jgy-agent-diff-begin dir)
    (jgy-agent-diff-test--write dir "new" "text\n")
    (let ((path (expand-file-name "new" dir)))
      (jgy-agent-diff-request (list path) (list (cons path 1))))
    ;; Pause just before diff starts to exercise iterator unwind cleanup.
    (let ((spawn (symbol-function 'make-process)) temporary)
      (cl-letf (((symbol-function 'make-process)
                 (lambda (&rest args)
                   (if (equal "diff" (car (plist-get args :command)))
                       (progn
                         (setq temporary (copy-sequence jgy-agent-diff--temporary))
                         (apply spawn (plist-put args :command '("sleep" "2"))))
                     (apply spawn args)))))
        (let ((deadline (+ (float-time) 5)))
          (while (and (not temporary) (< (float-time) deadline))
            (accept-process-output nil 0.01)))
        (should (= 2 (length temporary)))
        (jgy-agent-diff-cancel)
        (dolist (path temporary) (should-not (file-exists-p path)))))))
